### ISSUE TITLE
Bunny CDN Stream upload encoding failed

### ISSUE THREAD

**Issue by soixt** [cp6/BunnyCDN-API#23]
Do you maybe know what can be a encoding problem with uploading to the stream?
I tried sending file as file, file as base64 encrypted and base64 with data content..
```
$videoFile -> is laravel UploadedFile type.
$video = 'data:' . mime_content_type($videoFile->path()) .';base64,' . base64_encode(file_get_contents($videoFile));
```
For all 3 tries in bunny dashboard gallery it shows encoding failed on a video.. Reencoding do not work as well.

Tried with mp4, webm, avi files..

**Comment by grey-dev-0** [comment]
Hi there, I've across this amazing library and, faced the exact same issue so, I've debugged it and found some issues in the way the stream APIs are called, I've fixed it in a patch that can be easily accessed if you add the following block to your `composer.json` file.

```json
"repositories": [
    {
       "type": "vcs",
        "url": "https://github.com/grey-dev-0/BunnyCDN-API"
    }
],
```

Then in your terminal require the package again:

```
composer require corbpie/bunny-cdn-api
```

The changes I've done wasn't tested with all other APIs though so, if anyone finds another issue or confirms that everything is ok, please let me know so that I create a pull request for the fix to be included in the original package.

**Comment by cp6** [comment]
Sorry this is now fixed: https://github.com/cp6/BunnyCDN-API/commit/4b8293dfef07433f2c0532d2b8ad55184843c08a
